site_name: Solidity Scan Docs
docs_dir: documentation
theme:
  name: material
  font:
    text: Poppins
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  features:
    - navigation.instant
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/CredShields
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/credshields/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/credshields/
    - icon: fontawesome/brands/telegram
      link: https://t.me/solidityscan
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/9HhV4hGENw
extra_css: [assets/styles/style.css]

nav:
  - 'Introduction': index.md
  - 'Do a Quickscan of a Deployed Contract': quickscan.md
  - 'Scan a Project': project.md
  - 'Scan a Deployed Contract': block.md
  - 'Scan Solidity Files': filescan.md
  - 'Generate and Publish Reports': report.md
  - 'Integrations': integrations.md
  - 'Organisations': organisation.md

markdown_extensions:
  - pymdownx.tilde
